version: 2

report_sizes: true

builds:
  - env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}}
    main: ./cmd/tripflare/
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - darwin

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE
      - config.yaml.example

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc

release:
  github:
    owner: pilat
    name: tripflare
